---
title: "Bronchocela Morphology - FDA and SVM"
author: "Christian Supsup"
date: "28 March 2025"
output:
  html_document:
    df_print: paged
  pdf_document: default
indent: no
---
```{r setup, include=FALSE, message=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

**Load required packages/functions**
```{r load packages}
## Load required packages
required.packages <- c("mda", "ggplot2", "allocorR", "dplyr", "tidyverse", "ggbiplot",
                        "gridExtra", "ggpubr", "corrplot", "PCAtest", "nzilbb.vowels",
                        "ggrepel", "rpart", "rpart.plot", "caret", "caTools", "e1071", 
                        "scales", "RColorBrewer")

#devtools::install_github("arleyc/PCAtest")
#devtools::install_github("csupsup/nzilbb_vowels")

for (package in required.packages) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}

## Load our custom scripts from https://github.com/csupsup/morphR
library(morphR)
```

**Read and prepare data**
```{r read and prep}
## Read and prepare data
df.data.raw <- read.csv("data/bronchocela_morph_13March2025.csv")
df.data.sub <- subset(df.data.raw, select = c(6,11,12:35))
names(df.data.sub )[1] <- "Pop"
df.data.sub  <- df.data.sub [order(df.data.sub $Pop),]

## Remove populations with <4 individuals
df.data.sub  <- remove_pop(df.data.sub, grp = "Pop", threshold = 4)

## Correct body size measurements
df.mens.data <- subset(df.data.sub, select = c(1,3:16))
df.mens.data <- adjust_morph(df.mens.data , type = "multi_pop")

## Combine corrected measurements with meristic
df.mens.data <- cbind(df.mens.data[, 1], df.data.sub$Sex, df.mens.data[, -1])
colnames(df.mens.data)[1] <- "Pop"
colnames(df.mens.data)[2] <- "Sex"
df.comb <- cbind(df.mens.data, df.data.sub[17:26])

## Remove outliers per pop
df.comb  <- remove_outliers(df.comb, char = "SVL", grp = "Pop", q1 = 0.25, q3 = 0.75)
```

**Perform FDA and SVM**
```{r fda}
set.seed(122588)
options(scipen = 999)

## Combined data
df <- subset(df.comb, select = c(1,3:26))
df.c <- scale(df[, 2:ncol(df)]) # scale data
df.c <- data.frame(Pop = df$Pop, df.c)

## Male only
df <- df.comb[df.comb$Sex == "m",]
df$Sex <- NULL
df.m <- scale(df[, 2:ncol(df)])
df.m <- data.frame(Pop = df$Pop, df.m)

## Female only
df <- df.comb[df.comb$Sex == "f",]
df$Sex <- NULL
df.f <- scale(df[, 2:ncol(df)])
df.f <- data.frame(Pop = df$Pop, df.f)

## Assign fixed colors and shapes for Pop
point.shape <- c(
  "Borneo" = 8, "Lubang" = 11, "Luzon" = 10, "Mindanao" = 16, "Mindoro" = 17,
  "Moluccas" = 12, "Palawan" = 18, "Romblon" = 14, "Sumatra" = 23, "West Visayas" = 22
)

point.color <- c(
  "Borneo" = "#000000", "Lubang" = "#FF7F0E", "Luzon" = "#D62728", "Mindanao" = "#3D3178",
  "Mindoro" = "#1F77B4", "Moluccas" = "#9E1B32", "Palawan" = "#3A7B3B", 
  "Romblon" = "#235F90", "Sumatra" = "#6F196E", "West Visayas" = "#2F4F4F"
)

## Run FDA
fda.res.c <- run_fda(df.c, con.mat = TRUE, coef = TRUE, accu = TRUE, split = 0.7)
fda.res.c
fda.res.c <- run_fda(df.c, con.mat = TRUE, coef = TRUE, accu = TRUE, split = NULL)
fda.res.c

fda.res.m <- run_fda(df.m, con.mat = TRUE, coef = TRUE, accu = TRUE, split = 0.7)
fda.res.m
fda.res.m <- run_fda(df.m, con.mat = TRUE, coef = TRUE, accu = TRUE, split = NULL)
fda.res.m

fda.res.f <- run_fda(df.f, con.mat = TRUE, coef = TRUE, accu = TRUE, split = 0.7)
fda.res.f
fda.res.f <- run_fda(df.f, con.mat = TRUE, coef = TRUE, accu = TRUE, split = NULL)
fda.res.f

## Plot FDA results
fda.c <- plot_fda(df.c, point.color = point.color, 
              fixed.shape = point.shape, split = NULL)
fda.m <- plot_fda(df.m, point.color = point.color, 
              fixed.shape = point.shape, split = NULL)
fda.f <- plot_fda(df.f, point.color = point.color, 
              fixed.shape = point.shape, split = NULL)

pdf("results/broncho_fda.pdf", width = 5, height = 10)
ggarrange(fda.c, fda.m, fda.f,
  ncol = 1, nrow = 3, common.legend = TRUE, legend = "none", align = "hv")
dev.off()

## Perform FDA and SVM on unique lineages
df.sp <- df.c

df.sp$Pop <- gsub("Luzon|Lubang|Romblon|West Visayas", "B. marmorata", df.sp$Pop)
df.sp$Pop <- gsub("Mindoro", "B. carestii", df.sp$Pop)
df.sp$Pop <- gsub("Palawan", "B. mallarii", df.sp$Pop)
df.sp$Pop <- gsub("Mindanao", "B. philippina", df.sp$Pop)
df.sp$Pop <- gsub("Borneo", "B. cristatella s.l. (Borneo)", df.sp$Pop)
df.sp$Pop <- gsub("Sumatra", "B. cristatella s.l. (Sumatra)", df.sp$Pop)
df.sp$Pop <- gsub("Moluccas", "B. cristatella s.l. (Moluccas)", df.sp$Pop)

## Define the custom order for the 'Pop' column
pop.order <- c("B. carestii", "B. mallarii", "B. marmorata", "B. philippina", 
                "B. cristatella s.l. (Borneo)", "B. cristatella s.l. (Moluccas)", "B. cristatella s.l. (Sumatra)")

## Manually sort dataframe using the custom order
df.sp$Pop <- factor(df.sp$Pop, levels = pop.order)

## Run FDA on species level
fda.sp <- run_fda(df.sp, con.mat = TRUE, coef = TRUE, accu = TRUE, split = NULL)

## Plot FDA results 
point.shape <- c(
  "B. carestii" = 17, "B. mallarii" = 18, "B. marmorata" = 10, 
  "B. philippina" = 16, "B. cristatella s.l. (Borneo)" = 8,
  "B. cristatella s.l. (Moluccas)" = 12, 
  "B. cristatella s.l. (Sumatra)" = 23)

fda.sp <- run_fda_svm(df.sp, point.shape = point.shape, class.color = NULL, pop.order = pop.order)

fda.sp 

pdf("results/broncho_fda_svm_sp.pdf", width = 8, height = 5)
fda.sp
dev.off()
```