---
title: "Bronchocela Morphology - PCA and SVM"
author: "Christian Supsup"
date: "28 March 2025"
output:
  html_document:
    df_print: paged
  pdf_document: default
indent: no
---
```{r setup, include=FALSE, message=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
```

**Load required packages/functions**
```{r load packages}
## Load required packages
required.packages <- c("mda", "ggplot2", "allocorR", "dplyr", "tidyverse", "ggbiplot",
                        "gridExtra", "ggpubr", "corrplot", "PCAtest", "nzilbb.vowels",
                        "ggrepel", "rpart", "rpart.plot", "caret", "caTools", "e1071", 
                        "scales", "RColorBrewer")

#devtools::install_github("arleyc/PCAtest")
#devtools::install_github("csupsup/nzilbb_vowels")

for (package in required.packages) {
  if (!require(package, character.only = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}

## Load our custom scripts from https://github.com/csupsup/MorphoTax
library(MorphoTax)
```

**Read and prepare data**
```{r read and prep}
## Read and prepare data
df.data.raw <- read.csv("data/bronchocela_morph_13March2025.csv")
df.data.sub <- subset(df.data.raw, select = c(6,11,12:35))
names(df.data.sub )[1] <- "Pop"
df.data.sub  <- df.data.sub [order(df.data.sub $Pop),]

## Remove populations with <4 individuals
df.data.sub  <- remove_pop(df.data.sub, grp = "Pop", threshold = 4)

## Correct body size measurements
df.mens.data <- subset(df.data.sub, select = c(1,3:16))
df.mens.data <- adjust_morph(df.mens.data , type = "multi_pop")

## Combine corrected measurements with meristic
df.mens.data <- cbind(df.mens.data[, 1], df.data.sub$Sex, df.mens.data[, -1])
colnames(df.mens.data)[1] <- "Pop"
colnames(df.mens.data)[2] <- "Sex"
df.comb <- cbind(df.mens.data, df.data.sub[17:26])

## Remove outliers per pop
df.comb  <- remove_outliers(df.comb, char = "SVL", grp = "Pop", q1 = 0.25, q3 = 0.75)
```

**Perform PCA and SVM**
```{r pca}
set.seed(122588)
options(scipen = 999)

## Combined data
df <- subset(df.comb, select = c(1,3:26))
df.c <- scale(df[, 2:ncol(df)]) # scale data
df.c <- data.frame(Pop = df$Pop, df.c)

## Male only
df <- df.comb[df.comb$Sex == "m",]
df$Sex <- NULL
df.m <- scale(df[, 2:ncol(df)])
df.m <- data.frame(Pop = df$Pop, df.m)

## Female only
df <- df.comb[df.comb$Sex == "f",]
df$Sex <- NULL
df.f <- scale(df[, 2:ncol(df)])
df.f <- data.frame(Pop = df$Pop, df.f)

## Perform PCA
pca.res.c <- run_pca(df.c, prop.var = TRUE, var.load = TRUE, pts.load = TRUE)
pca.res.m <- run_pca(df.m, prop.var = TRUE, var.load = TRUE, pts.load = TRUE)
pca.res.f <- run_pca(df.f, prop.var = TRUE, var.load = TRUE, pts.load = TRUE)

## Assess PC and variable signifance using PCAtest
pca.sig.c <- PCAtest(df.c[2:ncol(df.c)], 1000, 
                        1000, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)

pca.sig.m <- PCAtest(df.m[2:ncol(df.m)], 1000, 
                        1000, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)

pca.sig.f <- PCAtest(df.f[2:ncol(df.f)], 1000, 
                        1000, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)

## Use "nzilbb_vowels"
pca.sig.c <- pca_test(df.c[2:ncol(df.c)], n = 1000, 
                scale = TRUE, variance_confint = .95, loadings_confint = 0.95)

p1 <- plot_variance_explained(pca.sig.c, pc_max = NA, percent = TRUE)
p2 <- plot_loadings(pca.sig.c, pc_no = 1, violin = FALSE, filter_boots = FALSE, 
                quantile_threshold = FALSE)
p3 <- plot_loadings(pca.sig.c, pc_no = 2, violin = FALSE, filter_boots = FALSE, 
                quantile_threshold = FALSE)

pca.sig.m <- pca_test(df.m[2:ncol(df.m)], n = 1000, 
                scale = TRUE, variance_confint = .95, loadings_confint = 0.95)

p4 <- plot_variance_explained(pca.sig.m, pc_max = NA, percent = TRUE)
p5 <- plot_loadings(pca.sig.m, pc_no = 1, violin = FALSE, filter_boots = FALSE, 
                    quantile_threshold = FALSE)
p6 <- plot_loadings(pca.sig.m, pc_no = 2, violin = FALSE, filter_boots = FALSE, 
                quantile_threshold = FALSE)

pca.sig.f <- pca_test(df.f[2:ncol(df.f)], n = 1000, 
                scale = TRUE, variance_confint = .95, loadings_confint = 0.95)

p7 <- plot_variance_explained(pca.sig.f, pc_max = NA, percent = TRUE)
p8 <- plot_loadings(pca.sig.f, pc_no = 1, violin = FALSE, filter_boots = FALSE, 
                quantile_threshold = FALSE)
p9 <- plot_loadings(pca.sig.f, pc_no = 2, violin = FALSE, filter_boots = FALSE, 
                quantile_threshold = FALSE)

ggarrange(p1, p2, p3, p4, p5, p6, p7, p8, p9,ncol =3, nrow=3, common.legend=TRUE, legend="right")

pdf("results/broncho_pca_sig.pdf",width = 16, height = 10 )
ggarrange(p1, p2, p3, p4, p5, p6, p7, p8, p9,ncol =3, nrow=3, common.legend=TRUE, legend="right")
dev.off()

## Use custom function "pca_svm_plot" to plot PCA results 
## Assign fixed colors and shapes for Pop
point.shape <- c(
  "Borneo" = 8, "Lubang" = 11, "Luzon" = 10, "Mindanao" = 16, "Mindoro" = 17,
  "Moluccas" = 12, "Palawan" = 18, "Romblon" = 14, "Sumatra" = 23, "West Visayas" = 22
)

point.color <- c(
  "Borneo" = "#000000", "Lubang" = "#FF7F0E", "Luzon" = "#D62728", "Mindanao" = "#3D3178",
  "Mindoro" = "#1F77B4", "Moluccas" = "#9E1B32", "Palawan" = "#3A7B3B", 
  "Romblon" = "#235F90", "Sumatra" = "#6F196E", "West Visayas" = "#2F4F4F"
)

pca.plot.c <- plot_pca(df.c, point.color = point.color, fixed.shape = point.shape)
pca.plot.m <- plot_pca(df.m, point.color = point.color, fixed.shape = point.shape)
pca.plot.f <- plot_pca(df.f, point.color = point.color, fixed.shape = point.shape)


ggarrange(pca.plot.c, pca.plot.m, pca.plot.f, ncol = 3, nrow = 1, 
  common.legend = TRUE, legend = "right", align = "hv") 

pdf("results/broncho_pca.pdf", width = 5, height = 10)
ggarrange(pca.plot.c, pca.plot.m, pca.plot.f, ncol = 1, nrow = 3, 
  common.legend = TRUE, legend = "none", align = "hv") 
dev.off()

## Perform PCA and SVM on unique lineages
df.sp <- df.c

df.sp$Pop <- gsub("Luzon|Lubang|Romblon|West Visayas", "B. marmorata", df.sp$Pop)
df.sp$Pop <- gsub("Mindoro", "B. carestii", df.sp$Pop)
df.sp$Pop <- gsub("Palawan", "B. mallarii", df.sp$Pop)
df.sp$Pop <- gsub("Mindanao", "B. philippina", df.sp$Pop)
df.sp$Pop <- gsub("Borneo", "B. cristatella s.l. (Borneo)", df.sp$Pop)
df.sp$Pop <- gsub("Sumatra", "B. cristatella s.l. (Sumatra)", df.sp$Pop)
df.sp$Pop <- gsub("Moluccas", "B. cristatella s.l. (Moluccas)", df.sp$Pop)

## Define the custom order for the 'Pop' column
pop.order <- c("B. carestii", "B. mallarii", "B. marmorata", "B. philippina", 
                "B. cristatella s.l. (Borneo)", "B. cristatella s.l. (Moluccas)", "B. cristatella s.l. (Sumatra)")

## Manually sort dataframe using the custom order
df.sp$Pop <- factor(df.sp$Pop, levels = pop.order)

## Run PCA on species level
pca.res.sp <- run_pca(df.sp, prop.var = TRUE, var.load = TRUE, pts.load = TRUE)

## Plot FDA results 
point.shape <- c(
  "B. carestii" = 17, "B. mallarii" = 18, "B. marmorata" = 10, "B. philippina" = 16, 
  "B. cristatella s.l. (Borneo)" = 8, "B. cristatella s.l. (Moluccas)" = 12, 
  "B. cristatella s.l. (Sumatra)" = 23)

pca.sp <- run_pca_svm(df.sp, point.shape = point.shape, class.color = NULL, pop.order = pop.order)

pca.sp

pdf("results/broncho.pca_svm_sp.pdf", width = 8, height = 5)
pca.sp
dev.off()

## Combine FDA and PCA plot
pdf("results/broncho_pca_fda_sp.pdf", width = 8, height = 8)
ggarrange(fda.sp, pca.sp, ncol =1, nrow=2, common.legend=FALSE, legend="right")
dev.off()
```
